name: Scaife-Ready

# Start CI when Commit is pushed to Master
on:
  push:
    branches: [ master ]
jobs:
  hooktest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     # Setup Python 
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
    # Display Version
      - name: Install Hooktest
        run: pip3 install HookTest
      - name: Run Hooktest
        run: hooktest ./ --console table --scheme epidoc --workers 3 --verbose 10 --countword
  release-on-push:
    runs-on: ubuntu-latest
    needs: hooktest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
